# Generated by Django 2.0.13 on 2021-10-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=10, verbose_name='퀴즈 푼 사람')),
                ('points', models.IntegerField(verbose_name='정답 개수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='문제')),
                ('option_1', models.CharField(max_length=10, verbose_name='선지1')),
                ('option_2', models.CharField(max_length=10, verbose_name='선지2')),
                ('option_3', models.CharField(max_length=10, verbose_name='선지3')),
                ('option_4', models.CharField(max_length=10, verbose_name='선지4')),
                ('option_5', models.CharField(max_length=10, verbose_name='선지5')),
                ('answer', models.IntegerField(verbose_name='정답')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=10, verbose_name='퀴즈 낸 사람')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizSet', verbose_name='퀴즈 셋 번호'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz_set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizSet', verbose_name='퀴즈 셋 번호'),
        ),
    ]
