# Generated by Django 2.0.13 on 2021-10-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211022_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='guest',
            field=models.CharField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '이름을 입력해주세요'}, max_length=10, verbose_name='퀴즈 푼 사람'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 문제의 정답 번호(1~5)를 입력해주세요'}, verbose_name='정답'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_1',
            field=models.CharField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 선택지를 입력해주세요'}, max_length=50, verbose_name='선택지1'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_2',
            field=models.CharField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 선택지를 입력해주세요'}, max_length=50, verbose_name='선택지2'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_3',
            field=models.CharField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 선택지를 입력해주세요'}, max_length=50, verbose_name='선택지3'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_4',
            field=models.CharField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 선택지를 입력해주세요'}, max_length=50, verbose_name='선택지4'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_5',
            field=models.CharField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 선택지를 입력해주세요'}, max_length=50, verbose_name='선택지5'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 선택지를 입력해주세요'}, max_length=100, verbose_name='문제'),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='host',
            field=models.CharField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '이름을 입력해주세요'}, max_length=10, verbose_name='퀴즈 낸 사람'),
        ),
    ]
