# Generated by Django 2.0.13 on 2021-10-29 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20211029_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 문제의 정답 번호(1~5)를 입력해주세요'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='정답'),
        ),
    ]
