# Generated by Django 2.0.13 on 2021-10-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211030_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], error_messages={'invalid': '적절한 값을 입력해주세요', 'required': '해당 문제의 정답 번호(1~5)를 입력해주세요'}, verbose_name='정답'),
        ),
    ]
